### ISSUE TITLE
POST

### ISSUE THREAD

**Issue by BWBuchanan7** [chaijs/chai-http#103]
This is a bit of a wall of text, but please bear with me:

Here is a POST attempt formatted using an entirely different toolchain for testing:

```
Time: Mon, 27 Jun 16 13:40:54 -0700
Source ip: 204.191.154.66

Headers (Some may be inserted by server)
REQUEST_URI = /post.php
QUERY_STRING = 
REQUEST_METHOD = POST
GATEWAY_INTERFACE = CGI/1.1
REMOTE_PORT = 19216
REMOTE_ADDR = 204.191.154.66
HTTP_CONNECTION = close
CONTENT_LENGTH = 64
HTTP_HOST = posttestserver.com
HTTP_TOKEN = text/plain
CONTENT_TYPE = application/x-www-form-urlencoded
UNIQUE_ID = V3GPVkBaMGUAAB1Uf04AAAAc
REQUEST_TIME_FLOAT = 1467060054.9575
REQUEST_TIME = 1467060054

Post Params:
key: 'grant_type' value: 'password'
key: 'username' value: 'hello@world.com'
key: 'password' value: 'password'
Empty post body.

Upload contains PUT data:
grant_type=password&username=hello%40world.com&password=password

```

And here is a POST attempt using Chai and Chai-HTTP:

```
Time: Mon, 27 Jun 16 13:47:29 -0700
Source ip: 204.191.154.66

Headers (Some may be inserted by server)
REQUEST_URI = /post.php
QUERY_STRING = 
REQUEST_METHOD = POST
GATEWAY_INTERFACE = CGI/1.1
REMOTE_PORT = 19275
REMOTE_ADDR = 204.191.154.66
HTTP_CONNECTION = close
CONTENT_LENGTH = 410
CONTENT_TYPE = multipart/form-data; boundary=--------------------------112369991749419303041318
HTTP_TOKEN = text/plain
HTTP_USER_AGENT = node-superagent/2.0.0
HTTP_ACCEPT_ENCODING = gzip, deflate
HTTP_HOST = posttestserver.com
UNIQUE_ID = V3GQ4UBaMGUAACUNdbQAAAAN
REQUEST_TIME_FLOAT = 1467060449.4647
REQUEST_TIME = 1467060449

Post Params:
key: 'grant_type' value: 'password'
key: 'username' value: 'hello@world.com'
key: 'password' value: 'password'
Empty post body.

== Multipart File upload. ==
Received 0 file(s)
```

Notice the difference in CONTENT_TYPE in particular (I think this is the source of my problem) where my previous tools would submit the POST using the 'application/x-www-form-urlencoded' format, Chai-HTTP seems to be using this 'multipart/form-data; boundary=--------------------------112369991749419303041318' format (which I understand about as well as I can resolve this issue on my own).

Am I somehow misusing Chai-HTTP's POST cababilities? Or does Chai-HTTP not allow for 'application/x-www-form-urlencoded' POST requests? I do not seem to be able to resolve this and it is the final hurdle for me to jump to make the transition to using a Mocha/Chai toolchain for my testing.

**Comment by keithamus** [comment]
Hey @BWBuchanan7 thanks for the issue.

You'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.

**Comment by BWBuchanan7** [comment]
Thanks keithamus, and my apologies for using the wrong medium for this question.

Should anyone else stumble across this issue in the future I have posted this question to Stack Overflow [here](http://stackoverflow.com/questions/38078569/seem-to-have-the-wrong-content-type-when-posting-with-chai-http).

**Comment by meeber** [comment]
@BWBuchanan7 That's just [super-agent](http://visionmedia.github.io/superagent/) (the http request library powering chai-http) auto-detecting the Content Type based on what kind of data you put in `.send`.

Your options:

1. As you noted in your SO reply, override the auto-detection by directly setting the header:

    ```js
    .set('content-type', 'application/x-www-form-urlencoded')
    ```

1. Use the `.type` method:

    ```js
    .type('form')
    ```

1. Use strings in `.send` instead of an object:

    ```js
    .send('grant_type=password')
    .send('username=hello@world.com')
    .send('password=password')
    ```

**Comment by BWBuchanan7** [comment]
@meeber Thank you very much for the clarification!

I actually just thought I'd experiment a little bit when I used .set() for the content-type and was quite surprised to learn that it worked to be honest. Having worked this out (and in particular finding out how much control I have over the requests I'm making) I think I'll be going forward with using Chai and Chai-Http for my team's testing.

If you don't mind my asking, is there somewhere I could have found such documentation about this usage of .set() .type() and .send() in particular? I wasn't even aware a type() method existed until now.
