### ISSUE TITLE
Question: adding express-session user property to chai-http request?

### ISSUE THREAD

**Issue by lsimmons2** [chaijs/chai-http#113]
Is there a way to add or manipulate properties of the `req` object in chai-http requests?

I want to test my API which uses express-session and authenticates any request based on the presence of the req.session.user object, as shown below:

    app.use(function(req, res, next) {
      if (req.session.user) {
      console.log('Authenticated request\n');
      next();
      } else {
        console.log('Request not authenticated, request rejected\n');    
        res.status(403).json({'message': 'Request rejected'});;
      }
    });

I'm writing tests for my API with chai-http as shown below:

    describe('test', function(){
     it('/test', function(done){
       chai.request(server)
       .get('/test')
       .end(function(err, res){
         res.body.should.be.a('object');
       });
     });
    });
Can I add the `.session.user` object to my chai-http requests so that they will pass the authentication?

Thanks!

**Comment by keithamus** [comment]
Hey @lsimmons2 thanks for the issue.

You'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

Having said that, express-session really just manages a session cookie - setting and reading the `cookie` and `set-cookie` headers. Take a look at our [readme on persisting cookies](https://github.com/chaijs/chai-http#retaining-cookies-with-each-request) for a good jumping off point.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.

**Comment by lsimmons2** [comment]
OK thanks for the help!
