### ISSUE TITLE
TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by JCornat** [chaijs/chai-http#153]
Hello !

I am facing an issue with `chai-http` in **3.0.0**, related to `superagent` package I think. It works with `chai-http` in **2.0.1**.

Here is the error on execution :

```
  Books
    /GET book
      1) it should GET all the books


  0 passing (24ms)
  1 failing

  1) Books /GET book it should GET all the books:
     TypeError: The header content contains invalid characters
      at ClientRequest.setHeader (_http_outgoing.js:374:11)
      at Test.Request.request (node_modules\superagent\lib\node\index.js:584:9)
      at Test.Request.end (node_modules\superagent\lib\node\index.js:673:18)
      at Context.it (test\test.js:14:18)
```

Here is my **test/test.ts file** :

```
process.env.NODE_ENV = 'test';

import * as chai from 'chai';
let chaiHttp = require('chai-http');
import { app } from '../app';
let expect = chai.expect;

chai.use(chaiHttp);

describe('Books', () => {
  describe('/GET book', () => {
    it('it should GET all the books', (done) => {
      chai.request(app)
        .get('/book')
        .end((err, res) => {
          expect(res).to.have.status(200);
          expect(res.body.ok).to.be.eq('OK');
          done();
        });
    });
  });
});
```

The error happend when I import a specific file in my **main app.ts file** :

```
import * as express from 'express';

/************************************\
// This line produce the error
import './middleware/prototypes';
\************************************/

export let app = express();

app.route("/book")
  .get((req, res) => {
    res.send({ok: 'OK'});
  });

app.listen(3000);
```

Here is **middleware/prototypes.ts file** :

```
interface Object {
  toArray(): any[];
}

Object.prototype.toArray = function(): any[] {
  let array = [];

  Object.keys(this).map((key) => {
    array.push(this[key]);
  });

  return array;
};
```

If I remove prototypes.ts import, it works. Here is the output :

```
  Books
    /GET book
      √ it should GET all the books


  1 passing (36ms)
```

Could you help me understand how can I fix ? :)
Thank you !

**Comment by vieiralucas** [comment]
Hello @JCornat, thank you for this issue.

I manage to dig down into `superagent` and understand why you are getting this error.

So, this is happening because you are adding a property `.toArray` to **every object** of your program by adding it to the  `Object.prototype` (you should really strive to not do this).

Because **every object** will have this new `.toArray` property [this for in](https://github.com/visionmedia/superagent/blob/9bacdbca150cd52c371a02c5c8f14152fcb94774/lib/node/index.js#L632) on superagent will try to add the header `toArray` to the request which will throw the TypeError.

This might be consider to be a bug in `superagent`. I will submit a PR to them adding a `.hasOwnProperty` guard to the `for in`

There is two things you can do to workaround this issue (I strongly recommend you to try the first)
1. **Do not add methods to Object.prototype**
2. You can add the method using `Object.defineProperty` passing `enumarable: false`, this will remove your property from the `for in`

```js
Object.defineProperty(Object.prototype, 'toArray', {
  enurable: false,
  value: function() {
    let array = [];

    Object.keys(this).map((key) => {
      array.push(this[key]);
    });

    return array;
  }
});
```

**Comment by JCornat** [comment]
Thank you @vieiralucas for the explanation !

Actually, I overload basic types' prototype **very occasionally**, (in this case it was to easily transform an object into an array), so I'm going to clean my code ! (Sadly, it was very convenient 😅)

**Comment by vieiralucas** [comment]
@JCornat No problem, I'm happy to help

You could use utility library like [lodash](https://lodash.com/) for those kind of things
For this specific case there is  [_.values(youObj)](https://lodash.com/docs/4.17.4#values)
