### ISSUE TITLE
How Test if server is running at port 8080

### ISSUE THREAD

**Issue by giper45** [chaijs/chai-http#161]
I'd like to test if localhost server is running at port 8080 before to start testing. Is there some function in order to do this? 
Thanks in advance!

**Comment by keithamus** [comment]
Hi @giper45 thanks for the issue.

If it is an `require('http').Server`, like express or connect then you can run `app.address().port` to get the running port. 

That's all the support we can give you I'm afraid. You'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
