### ISSUE TITLE
Nock or equivalent to mock requests?  

### ISSUE THREAD

**Issue by dman777** [chaijs/chai-http#162]
Love chai-http requests....great stuff! 

How can I mock requests with chai-http? I tried Nock but the real request still goes out:

mocha helper.js
```javascript
process.env.NODE_ENV = 'test';
var chai = require('chai');
var request = require('supertest');
var server = require('../server_dev');
var sinonChai = require("sinon-chai");
var chaiHttp = require('chai-http');
var nock = require('nock');


chai.use(chaiHttp);

var should = chai.should();

const pg = require('../app/data/init-db.js');


global.chai = chai;
global.server = server;
global.pool = pg.pool;
global.should = should;
global.nock = nock;
```

-------------------------------------------------------

```javaScript

  describe('When entering zipcode', ()=> {
    it('should return city, state, lat, and lng', (done) => {
      nock('http://localhost:7075')
        .get('/api/v1/city-state')
        .reply(401, {
          "foo": "foo"
        });

      chai.request(server)
        .get('/api/v1/city-state')
        .query({zipcode: '78857'})
        .set('cookie', cookie)
        .set('signedIn', 'true')
        .end((err, res) => {
          res.should.have.status(200);
          done();
        });
    });
  });
```

**Comment by keithamus** [comment]
Hey @dman777 thanks for the issue.

Personally; I have nock working locally with chai.http - so it definitely works. If you're attempting to use nock to stub out the server - then it should match the server hostname and port. If you're passing an Express/Connect/HTTP server to `chai.request` then it'll boot it up on a random port (see here: https://github.com/chaijs/chai-http/blob/master/lib/request.js#L254). So you'll need nock to match.

Sadly; I don't have much more time to look at this. You'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.

**Comment by dman777** [comment]
That was it.... I pass express server to `chai.request(app)` because it is the cleanest way to bounce with `mocha --watch` and not have a hanging connection. 

I would like to say that this would be a critical feature to be able to control port for this use case.

**Comment by keithamus** [comment]
You are welcome to chose the port - by not letting chai do it for you. Simply run `server.listen(7075)` before you call `chai.request(server)`.
