### ISSUE TITLE
Configuring chai-http to talk to mochawesome

### ISSUE THREAD

**Issue by snoblenet** [chaijs/chai-http#163]
The `mochawesome` custom mochajs reporter lets you provide contextual information like [this](https://github.com/adamgruber/mochawesome#adding-test-context):

`addContext(this, 'http://www.url.com/pathname');`

I'd like to configure `chai-http` globally so that every request adds the full URL as context.

Is this possible? Thanks.

**Comment by austince** [comment]
Hey @snoblenet, going through some old issues. I think it's an interesting idea but since `chai` is not opinionated about which testing framework is used, this integration would make more sense as a separate package - happy to talk about what you might need to hook into for that to happen, but going to close this for now.
