### ISSUE TITLE
Testing CORS?

### ISSUE THREAD

**Issue by andrewspiers** [chaijs/chai-http#176]
Hi, and thanks for this very useful plugin.
Is it possible to use this library to test that the Access-Control-Allow-Origin and
Access-Control-Allow-Methods are set by using an http OPTIONS request?

I have tried something like:

```
describe('OPTIONS /example', () => {
  it('OPTIONS should return access-control headers', function (done) {
    chai.request(app)
    .post('/example')
    .field('_method', 'options')
    .end(function (err, res) {
```

but it doesn't seem to work. Maybe this is a feature request?

**Comment by keithamus** [comment]
Hey @andrewspiers thanks for the issue.

You can simply make an `options` request and test the headers:

```js
describe('OPTIONS /example', () => {
  it('OPTIONS should return access-control headers', () => {
    return chai.request(app)
      .options('/example')
      .then((res) => {
        expect(res).to.have.header('Access-Control-Allow-Origin', '*')
        expect(res).to.have.header('Access-Control-Allow-Methods', 'POST, GET, OPTIONS')
      })
  })
})
```

If you have any other questions like this; you'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
