### ISSUE TITLE
Ability to remove auto generated headers.

### ISSUE THREAD

**Issue by ben-crowhurst** [chaijs/chai-http#200]
I'm testing a new RESTful service and I'd like to remove the `Content-Type` header so one might get a 415 (Unsupported Media Type) response.

The example below forces the `Content-Type` header set to `application/x-www-form-urlencoded`.

``` javascript
chai.request(service)
    .post('/attachments')
    .set('Content-Type', null)
    .send('Attachment Data Here 12334566')
    .end((error, response) => {
           should.exist(error);
           response.status.should.equal(415);
           cache.length().should.equal(0);
           done();
    });
```

Is this possible?

**Comment by keithamus** [comment]
Hey @ben-crowhurst thanks for the issue.

`.send` will set the `Content-Type` header if it isn't present (or is `null`). You should try `set`ing it after calling `send`.

```js
chai.request(service)
    .post('/attachments')
    .send('Attachment Data Here 12334566')
    .set('Content-Type', null)
    .end((error, response) => {
           should.exist(error);
           response.status.should.equal(415);
           cache.length().should.equal(0);
           done();
    });
```

Sorry to say I wont be able to help any more than this; in the future, you may have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.

**Comment by ben-crowhurst** [comment]
@keithamus Thanks for the speedy reply.  I tried an assortment of different configurations, including after send, with no luck.

Thanks for your time.

**Comment by keithamus** [comment]
@ben-crowhurst Chai-HTTP is really just a wrapper over https://github.com/visionmedia/superagent. So check out their issue tracker, docs, or code - it might have some insight for you!

**Comment by keithamus** [comment]
A quick look - maybe this will work:

```js
chai.request(service)
    .post('/attachments')
    .send('Attachment Data Here 12334566')
    .unset('Content-Type')
    .end((error, response) => {
           should.exist(error);
           response.status.should.equal(415);
           cache.length().should.equal(0);
           done();
    });
```

**Comment by ben-crowhurst** [comment]
You are a Gentleman and a Scholar. 

Where is your 'buy me a beer' link?

**Comment by keithamus** [comment]
Why, there is one right here: https://opencollective.com/chaijs 😆
