### ISSUE TITLE
method as a variable

### ISSUE THREAD

**Issue by peeyushsrj** [chaijs/chai-http#210]
I am automating tests using `chai-http`. It provides methods for request types as `get`, `post`, `put` etc. But how can I do something like 
```
chai.request(url)
       .method("POST")
```
in chai-http. I have seen the documentation + already opened issue, didn't find solution. Please help.

**Comment by keithamus** [comment]
Hey @peeyushsrj thanks for the issue.

Would `chai.request(url)["post"]()` not work for you? At any rate - you may habe much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.

**Comment by HanHyeoksu** [comment]
If you want to use function using string then how about this way?
```
chai.request(url)['post']()
```
