### ISSUE TITLE
Chai-HTTP 4.0.0 not correctly handling errors

### ISSUE THREAD

**Issue by rodmaz** [chaijs/chai-http#211]
`chai-http` 4.0.0 does not correctly handle errors. In `chai-http` 3.x.x, HTTP errors (3xx, 4xx, 5xx) are returned in the callback parameter (`err`). Under `chai-http` 4.0.0, when server returns an error, error objects in callback are `null`.

Example below works fine with `chai-http` 3.x.x (return a valid `err` object) but fails with `chai-http` 4.0.0 (`err` object is null).
```
  it('retrieve objects w/o authentication; expected result: Unauthorized (401)', (done) => {
    chai.request(expressApp).get('/api/v1.0/retrieve-objects')
      .end((err, result) => {
        chai.assert.isNotNull(err);
        chai.expect(result).to.have.status(401);
        done();
      });
  });
```

**Comment by keithamus** [comment]
Hey @rodmaz thanks for the issue.

This is intentionally part of the breaking changes that were released with chai@4. We don't want to error based on the status code, especially as we are a testing library and an error state typically means "tests have failed". Instead as long as the request completes - regardless of status - it will not have an `err`. 

[Here are the release notes for 4.0](https://github.com/chaijs/chai-http/releases/tag/4.0.0)

I'll close this as this was an intentional change, and so there is no bug here. Feel free to continue the discussion though 😃

**Comment by damianb** [comment]
In all honesty, this is a sign that you have poorly communicated breaking changes.  

You have a [history file](https://github.com/chaijs/chai-http/blob/master/History.md) that is sorely out of date (last updated at 2014-10-08 for 1.0.0) for several versions ago containing a deprecation message which is referring users to check your [commit logs](https://github.com/chaijs/chai-http/commits/master) which contain no readily accessible information on breaking changes.

Please review how you handle disclosing changelogs, as right now you're communicating three possible venues with only one that is actually correct.

Perhaps state it outright in the README where to find release notes and remove the History.md file entirely?
