### ISSUE TITLE
Handle middleware using chai-http

### ISSUE THREAD

**Issue by Qubaish** [chaijs/chai-http#213]
Hi guys, I am facing issue I am testing an api using chai-http but it struck in middlewear means it does not call next() function. Not sure how to handle this, little guide may be helps me alot. Here is my code may be it helps you understand better. 

**Middleware**
```
function middleware(req, res, next) => {
  // doing some stuff
  console.log("step 1") // prints
  next()
}
```
**API**
```
router.get('/orders', middleware, (req, res) => {
  // some stuff
 console.log("step 2") // not prints
 res.send(result)
})
```
**Test Case**

```
  let order = new Order(mockOrder);
  order.save((err, order) => {
    chai.request(server)
    .get('/orders')
    .end((err, res) => {
    // some stuff
   })
  })
```

**Comment by keithamus** [comment]
Hey @Qubaish thanks for the issue.

This looks like it is not a bug with chai-http. If your middleware isn't working correctly I'd suggest you look up the documentation for the web framework you're using (you haven't mentioned which framework you're using - I guess it's express?). Although I haven't run your example code (I'm afraid I don't have time) nothing looks wrong with it - so maybe it's the `// doing some stuff` part that is going wrong?

I think you'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
