### ISSUE TITLE
Asserting response of js file

### ISSUE THREAD

**Issue by ryanto** [chaijs/chai-http#228]
I need to test that some text exists in a javascript file, but I'm unsure how to assert the response of an `application/javascript` content type. Both `res.body` and `res.text` are empty.

```js
let res = await chai.request(app).get('/assets/sample.js');

expect(res.?).to.equal("function(){}");
```

Is there a function or property on `res` that I can use to get the response from the server?

Thanks!

**Comment by keithamus** [comment]
Hey @ryanto thanks for the issue.

`res.text` should be the thing you need, I believe.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.

**Comment by sw360cab** [comment]
I suggest reopening this issue...

As stated [here](https://stackoverflow.com/questions/43324004/chai-doesnt-recognize-content-type-application-javascript), using res.text only work for content-type: "text/javascript", but not for "application/javascript"

Since "application/javascript" is the right content-type to go for js files as stated by [W3C](http://www.rfc-editor.org/rfc/rfc4329.txt) 

> text/javascript (Obsolete): JavaScript; Defined in and made obsolete in RFC 4329 in order to discourage its usage in favor of application/javascript. However, text/javascript is allowed in HTML 4 and 5 and, unlike application/javascript, has cross-browser support. The "type" attribute of the tag in HTML5 is optional and there is no need to use it at all since all browsers have always assumed the correct default (even in HTML 4 where it was required by the specification).

I think it would be nice to find its content somewhere in the res object when using chai-http

**Comment by austince** [comment]
@sw360cab it might be prudent to look into moving to 'application/javascript', but in the meantime, does this issue help you at all? https://github.com/chaijs/chai-http/issues/249

**Comment by sw360cab** [comment]
@austince Ohhhh Yesss.

It does works like a charm... I did my best to find this out or documented somewhere but I could not.
Thank you!
