### ISSUE TITLE
Add typings for chai-as-promised integration

### ISSUE THREAD

**Issue by dawsonc623** [chaijs/chai-http#237]
I am trying to use `chai-http` with `chai-as-promised` to be able to write cleaner assertions. I want to be able to write something like this:

```
it("responds with status code 200", function() {
  return chai.request(app)
    .get("/")
    .should.eventually.have.status(200);
});
```

Functionally, this works perfectly. However, to get TypeScript to compile it, I had to add this to my code:

```
// Add chai-http typings to chai-as-promised
declare global
{
  namespace Chai
  {
    interface PromisedAssertion
    {
      status(code : number): PromisedAssertion;
    }
  }
}
```

Once I added that, everything worked like a charm. It would be handy if `chai-http` extended the `PromisedAssertion` interface with all of its properties as it does with `Assertion`. If you think this is something `chai-as-promised` should be handling instead, I can make this request there instead (although I can see that ballooning to "`chai-as-promised` must be responsible for supporting all libraries", which I imagine they would prefer not to have happen).

**Comment by austince** [comment]
Hey, thanks for the request! I definitely see your use case, but since `chai-as-promised` is not a dependency of this package and since the `status` check is synchronous, I don't think just adding that typing fits within this library. Whether or not to incorporate `chai-as-promised` support is a different discussion that would need input from the community.

Though a few extra lines, I don't think the overhead is massive or much less readable:
```ts
it("responds with status code 200", function() {
  return chai.request(app)
    .get("/")
    .then(function (req) {
        req.should.have.status(200);
    });
});
```

**Comment by dawsonc623** [comment]
@austince Thanks for the reply. For the time being I am maintaining the typings I need myself; it is not a lot of work, and while your solution works perfectly and reads well enough, I like how my original reads better. I am not sure how often `chai-as-promise` and `chai-http` are used together, but if it is (or becomes) common you should definitely consider this request.

**Comment by austince** [comment]
@dawsonc623 your solution certainly reads nicely! Just worried about the overhead of maintaining types for something that is not a dependency, but it'd definitely be beneficial to the conversation to understand how often they are used together.

**Comment by damianb** [comment]
Personally, I have avoided `chai-as-promised` altogether and have instead been using async/await, as mocha+chai will accept an async function for the test body parameter of `it` without issue for running tests.

Which results in something like this:

``` ts
it('should error when viewing a nonexistent tag', async () => {
  const res = await chai.request(server)
    .get('/tag/0')
    .set('Authorization', token)

  expect(res).to.have.status(404)
  // ...
})
```

...which is quite useful, considering that it's entirely reasonable to then also run additional expects on things such as returned headers, the response body structure, contents, and so on afterwards.

**Comment by vieiralucas** [comment]
I think that `chai-as-promised` only shines when you want to test that a `Promise` rejects.
For other cases, IMO,  it's better to write the tests like @damianb suggested since test runners will fail the test if the `Promise` returned rejects.

I'm pretty sure that everytime the `chai-http` `Promise` rejects you want your test to fail. So I don't think that there is a strong case for using `chai-as-promised` with `chai-http` so that we should add typings to `chai-http` just for `chai-as-promised`.
