### ISSUE TITLE
Done is not executed, test does ot finish

### ISSUE THREAD

**Issue by Ruudii8** [chaijs/chai-http#238]
Hello,
there are already some issues and threads with a similar problem, but no workaround seem to fix my problem. 
My chai.request gets executed succesfull but it seems done() is not executed, because even though all tests are executed the script always needs to be stopped manually.
My code is: 

```javascript
import {expect} from 'chai'
import { app } from '../../src/ui/express'
import { config } from '../../src/config'
var chai = require('chai')
var chaiHttp = require('chai-http')
chai.use(chaiHttp)

describe("Server", () => {
    it("can request config", function(done) {
        chai.request(app)
        .get('/config')
        .then( (res: any) => {
            expect(res.text).to.equal(JSON.stringify(config))
            done()
        })
        .catch( (err: any) => {
            done(err)
        })
    })
})
```

Am I doing something wrong or do I forget something?

Thanks & Greetings

**Comment by keithamus** [comment]
Hey @Ruudii8 thanks for the issue.

There's nothing that looks wrong from your code, so sadly I can't really diagnose the problem without seeing either a reduced test case or if you could point me to the repository so I could run it locally and diagnose it.

What I would suggest though; if you instead `return chai.request(app)` then you can omit `done` entirely, as Mocha (which I presume you're using) will read the promise and do what it needs to:

```js
import {expect} from 'chai'
import { app } from '../../src/ui/express'
import { config } from '../../src/config'
var chai = require('chai')
var chaiHttp = require('chai-http')
chai.use(chaiHttp)

describe("Server", () => {
    it("can request config", function() {
        return chai.request(app)
        .get('/config')
        .then( (res: any) => {
            expect(res.text).to.equal(JSON.stringify(config))
        })
    })
})
```

I'll close this issue for now - but if the above doesn't fix your problem, then if you could come back with a reduced test case or a link to a repo that'd be great 😄

**Comment by Ruudii8** [comment]
It's still not working. The full code is in a private repository but I uploaded all relevant files in a public repository:
https://github.com/Ruudii8/testing-demo

Already thank you for the help!

**Comment by Ruudii8** [comment]
@keithamus Can you take a look to the repo and reopen the issue?

**Comment by keithamus** [comment]
@Ruudii8 this is not due to Chai, but due to Express+Mocha. You've called [`app.listen`](https://github.com/Ruudii8/testing-demo/blob/master/src/ui/express.ts#L16-L19) within the express  code which will open the web server and does not shut it down until you manually call `server.close` (where `server` is the return value from `app.listen()`). Mocha will not shut down these extra services for you.

You might want to consider moving the `app.listen()` call to another part of your code which does not get loaded into your tests, for example [in your index.js file](https://github.com/Ruudii8/testing-demo/blob/master/index.js#L6)
