### ISSUE TITLE
Add easy testing for XML and Javascript content-types, and UTF-8 charset

### ISSUE THREAD

**Issue by nfreear** [chaijs/chai-http#26]
I love the existing support for JSON, HTML and text:

``` js
expect(req).to.be.html;
```

I propose extending this:

``` js
expect(req).to.be.xml;
expect(req).to.be.javascript;
```

The proposed solution makes some assumptions:
1. The expected content-type for XML is `application/xml`
2. The expected content-type for Javascript is `text/javascript` - I suggest this is still the norm on servers despite `application/javascript` being more correct.

I'm also interested in testing the character encoding:

``` js
expect(res).to.be.utf8;   // Check for "charset=UTF-8" - case sensitive :(
```

My use-case is [@nfreear/ou-media-player-test ../test/ou-podcast-test.js](https://github.com/nfreear/ou-media-player-test/blob/master/test/ou-podcast-test.js#L32)

Thoughts?

**Comment by keithamus** [comment]
Hey @nfreear thanks for the issue! You're totally right, we could extend these a bunch. If you fancy making a pull request - I'd love to see it. 

For some ideas about a PR - you could use [node-mime](https://github.com/broofa/node-mime) and override the [`var contentTypes` declaration in http.js](https://github.com/chaijs/chai-http/blob/master/lib/http.js#L45-L49) to use node-mimes list. (Node mime is a dependency of SuperTest/Agent anyway, so you wouldn't be introducing a new dependency per se.)

So the final code might look something like:

```js
var contentTypes = require('mime').types
```

This may be overkill though, as currently node-mime has 998 mime-types in `mime.types`.

As for charsets - personally I think they should be a little more explicit, as to not conflict with mimetypes, and because the assertion method would be easier:

```js
expect(res).to.have.charset('utf-8')
```

The `charset` method could then use node-mime's `mime.charset.lookup` method and pass in the Content-Encoding header, something like

```js
chai.addMethod('charset', function (value) {

   this.assert(
      mime.charset.lookup(flag(this, 'obj')).toLowerCase() === value.toLowerCase()
   );
});
```

Thoughts?

**Comment by keithamus** [comment]
@nfreear you've all but nailed it. We can use node-mime and have both `.mime` and `.charset` assertions for the broad cases, and have a couple of convenient aliases which call out to `.mime`, so here's my suggestion:

- Add a `mime` method which asserts using something like `mime.extension(flag(this, 'obj').headers['content-type']) === value`
- Add a `charset` method which asserts using something like `mime.charset.lookup(flag(this, 'obj').headers['content-type']) === value`
- Refactor the [`contentTypes` object](https://github.com/chaijs/chai-http/blob/master/lib/http.js#L45-L49) to be something like `shortcutContentTypes` - perhaps as an array of content type names?
- Refactor `checkContentType` to use the `.to.be.mime`

So the end result will look something like:

```js
expect(res).to.have.charset('utf-8') 
expect(res).to.have.mime('js')
expect(res).to.be.js // shortcut for .to.have.mime('js')
```

`.mime` could either use `node-mimes` lookup list (so pass extension name rather than full mimetype) or the full explicit mimetype, perhaps it could do both by first looking up the value through node-mime and then defaulting to just using it explicitly? This way you could do both

```js
expect(res).to.have.mime('css')
expect(res).to.have.mime('text/css') // same assertion as above
```

**Comment by keithamus** [comment]
Hey @nfreear did you get anywhere with this?

**Comment by jameswlane** [comment]
Instead of opening a new issue I am just commenting on here. 

I would really love to see XML support for plugin. Started working on a new project and I thought this `chai-http` would be perfect for testing the API, but it's in XML.

I would love to help contribute to get XML support if needed.
