### ISSUE TITLE
Security Vulnerability: Update superagent Version to Fix!

### ISSUE THREAD

**Issue by takwas** [chaijs/chai-http#277]
There are [known issues](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=jQuery) with jQuery versions before [v3.5.0](https://www.npmjs.com/package/jquery/v/3.5.0). 

This resulted in the flagging of supergent versions prior to [v6.0.0](https://github.com/visionmedia/superagent/releases/tag/v6.0.0), where [a fix](https://github.com/visionmedia/superagent/pull/1582) has been applied.

Therefore, this library can be updated to use the [latest version](https://www.npmjs.com/package/superagent/v/6.1.0) of superagent in order to fix vulnerability reports on this library based on its usage of superagent.

**Comment by austince** [comment]
I know we've been hesitant to upgrade superagent before (see https://github.com/chaijs/chai-http/issues/203) because we've contemplated dropping in favor of just `fetch`, though these efforts have stalled (my bad). That being the case, I would be on board with a PR upgrading superagent if there are not too many breaking changes. Is this something you would be interested in tackling?

**Comment by jakebrown58** [comment]
I see that super-agent was upgraded to 6.1, but that the library is still on 4.3.0, and thus when we do a fresh upgrade from the registry, it still pulls in the old version of 4.3.0 with super-agent 3.7.x, and the jQuery 3.2.1 which is flagged for security issues.
