### ISSUE TITLE
reading response's data / response data event

### ISSUE THREAD

**Issue by gnrlbzik** [chaijs/chai-http#32]
Is there a way to read response's data? Or am I missing something?

I have a proxy server functionality that i need to test and I would like to compare two json files. I tried res.on('data' but it seams that mocha finishes run before hand.

**Comment by keithamus** [comment]
Hey @gnrlbzik thanks for the issue.

The documentation describes two easy ways to deal with the response. The [traditional callback way, using .end()](https://github.com/chaijs/chai-http#dealing-with-the-response---traditional) and the [promise way, using .then()](https://github.com/chaijs/chai-http#dealing-with-the-response---promises). Below is the relevant info. If you have any more trouble with this let me know and I'll explain further.

#### Dealing with the response - traditional

To make the request and assert on its response, the `end` method can be used:

```js
chai.request(app)
  .put('/user/me')
  .send({ passsword: '123', confirmPassword: '123' })
  .end(function (err, res) {
     expect(err).to.be.null;
     expect(res).to.have.status(200);
  });
```

#### Dealing with the response - Promises

If `Promise` is available, `request()` becomes a Promise capable library -
and chaining of `then`s becomes possible:

```js
chai.request(app)
  .put('/user/me')
  .send({ passsword: '123', confirmPassword: '123' })
  .then(function (res) {
     expect(res).to.have.status(200);
  })
  .catch(function (err) {
     throw err;
  })
```

Since Node.js version 0.10.x and lower does not have native promise support you can use [kriskowal/q](https://github.com/kriskowal/q) for them. Use the `addPromise` function to do this. For example:
```js
var chai = require('chai');
chai.use(require('chai-http'));

// Add promise support if this does not exist natively.
if (!global.Promise) {
  var q = require('q');
  chai.request.addPromises(q.Promise);
}
```

**Comment by gnrlbzik** [comment]
Thank you @keithamus, did not expect you would get back to me so quickly :+1:  I will work through examples and get back to you.
