### ISSUE TITLE
Multiple parameter

### ISSUE THREAD

**Issue by asarr** [chaijs/chai-http#37]
Hi there,

I've been trying to send a request with a param list:

chai.request("myUrl").get("/v1/skus?id=123&id=456")...

this request got encoded and the server receives id[0]=123&id[1]=456 which is totally different than the expected format by the server.

Otherwise - using .query({id: "123", id: "456"}) or 
.query({id: "123"})
.query({id: "456"})
override the initial value so only one param is getting sent.

Is there any reason the query param list get encoded ? 
I might be doing it wrong - in this case could you please advice how to pass multiple param values ?

Cheers

**Comment by pgrm** [comment]
sorry, but how are you accessing the params on the server? - maybe I'm missing here something, the way it gets encoded seems valid for me.

**Comment by asarr** [comment]
I am not responsible of the backend server but it is expecting a list of ids (id=a&id=b), rather than an array of id (how it gets encoded at the moment).

Thanks to http spec, multiple value should be one of the format:

- id=a&id=b&id=c
- id=a,b,c

I am not saying the way it gets encoded is wrong, but when I pass d=a&id=b&id=c , I am not expecting it to be encoded prior sending the request.

**Comment by pgrm** [comment]
Ok, anyway - this is probably not the library where you want to report the error. chai-http is merely using superagent and combining it with chai. So I think, [superagent](https://github.com/visionmedia/superagent) is handling everything about http requests and you should ask there. Afterwards, if it's a bug and they fix it, you'll still need to check if chai-http will use the new version of superagent, otherwise update the dependency.

**Comment by asarr** [comment]
Thanks a lot.
Amazing work on chai-http by the way - absolutely love it !

**Comment by keithamus** [comment]
Thanks for picking this up @pgrm. I'll close this as you're right, this is likely to be an upstream issue.
