### ISSUE TITLE
why doesn't this fail?

### ISSUE THREAD

**Issue by mjhea0** [chaijs/chai-http#45]
Curious why the tests are passing? 

https://github.com/mjhea0/real-time-markdown

if you look at the POST route it's nested inside the GET route. This should be getting a 404. In fact if you comment out the first test it fails. 

https://github.com/mjhea0/real-time-markdown/blob/master/server/routes/api.js#L15

Thanks.

**Comment by keithamus** [comment]
Hey @mjhea0 thanks for this.

You might have a better time asking this kind of question on [Stack Overflow](https://stackoverflow.com/). This issue tracker is more for bugs and feature requests.

If you think the test passing is an actual bug within chai-http, then could you please provide a reduced test case, or try to describe what the actual bug is, and then we can look to fixing it. I'll close this issue for now, if you have more to add feel free to continue to comment, and I'll reopen it if it becomes a valid bug :smile:

**Comment by mjhea0** [comment]
Thanks, @keithamus. I do think it is a bug within chai-http.

The [routes](https://github.com/mjhea0/real-time-markdown/blob/master/server/routes/api.js#L15) are written incorrectly (the POST is nested within the GET, so it should 404):

```javascript
router.get('/posts', function(req, res, next) {
  Post.find(function(err, data){
    if(err){
      res.json({'ERROR' : err});
    } else {
      res.json(data);
    }
  });

  router.post('/posts', function(req, res, next){
    console.log('testing post route - take 1');
    newPost = new Post({
      title : req.body.title,
      description : req.body.description,
      content : req.body.content
    });
    newPost.save(function(err, data){
      if(err){
        console.log('testing post route - take 2');
        res.json({'ERROR' : err});
      } else {
        console.log('testing post route - take 3');
        res.json({'SUCCESS' : data});
      }
    });
  });

});
```

However, the [tests](https://github.com/mjhea0/real-time-markdown/blob/master/test/test-server.js#L32) still pass:

```javascript
  it('should add a single blog post on /posts', function(done){
    chai.request(server)
    .post('/api/v1/posts')
    .send({'title': 'This Is The test title for posts', 'description' : 'This is where I describe stuff', 'content' : 'This is where the content goes' })
    .end(function(err, res){
      console.log(res.body.SUCCESS);
      res.should.have.status(200);
      res.should.be.json;
      res.body.should.be.a('object');
      res.body.SUCCESS.should.have.property('title');
      res.body.SUCCESS.should.have.property('description');
      res.body.SUCCESS.should.have.property('content');
      res.body.SUCCESS.should.have.property('_id');
      res.body.SUCCESS.title.should.equal('This Is The test title for posts');
      res.body.SUCCESS.description.should.equal('This is where I describe stuff');
      done();
    });
  });
```

**Comment by keithamus** [comment]
@mjhea0 Is it intentional that `router.get()` sets up `router.post()`? Seems like that code is wrong. At any rate this will mean that your tests cant be run in isolation - this test is probably passing because [you've already run the `get` in the test above](https://github.com/mjhea0/real-time-markdown/blob/master/test/test-server.js#L32) and therefore `router.post` has been set up by the next test runs.

Swap the `get` and `post` tests around and I bet the post one fails. Solution: don't add new routes to express dynamically, it makes them hard to test :smile:

**Comment by mjhea0** [comment]
@keithamus so each route was added separately, but the student writing the code accidentally nested the routes, then wrote the POST test and got a false positive. It should have 404'ed. So, you have to write your code correctly in order for the tests to work correctly. That defeats the purpose of writing tests. :)
